# tutor_words.py

letter_words = {
    "a": ["apple", "apricot", "banana", "grape"],
    "b": ["banana", "blueberry", "blackberry", "box"],
    "c": ["cherry", "cloud", "car", "cat"],
    "d": ["dog", "dragon", "daft", "desk"],
    "e": ["elephant", "lemon", "tree", "peach"],
    "f": ["fox", "forest", "fence", "fish"],
    "g": ["grape", "garden", "grizzly", "golf"],
    "h": ["house", "hill", "how", "hat"],
    "i": ["igloo", "ice", "ink", "island"],
    "j": ["judge", "jumps", "jam", "jelly"],
    "k": ["kite", "king", "keyboard", "kitchen"],
    "l": ["lemon", "lazy", "lion", "lake"],
    "m": ["mango", "mountain", "melon", "mouse"],
    "n": ["night", "nail", "nest", "nap"],
    "o": ["orange", "octopus", "olive", "onion"],
    "p": ["peach", "pineapple", "pear", "plum"],
    "q": ["quartz", "queen", "quick", "quiz"],
    "r": ["river", "rabbit", "rose", "rock"],
    "s": ["sphinx", "strawberry", "sun", "ship"],
    "t": ["tree", "tiger", "tulip", "train"],
    "u": ["umbrella", "unicorn", "up", "use"],
    "v": ["vex", "valley", "violet", "van"],
    "w": ["wolf", "window", "water", "wheel"],
    "x": ["xylophone", "xerox", "xenon", "box"],
    "y": ["yellow", "yarn", "yard", "yogurt"],
    "z": ["zebra", "zoo", "zigzag", "zone"]
}


# tutor_words.py (continued)

combination_words = {
    # A Transitions
    "aa": ["aardvark", "bazaar"], "ab": ["about", "absorb"], "ac": ["accept", "acid"],
    "ad": ["adult", "added"], "ae": ["aerial", "aesthetic"], "af": ["after", "afraid"],
    "ag": ["again", "agree"], "ah": ["ahead", "sahara"], "ai": ["train", "claim"],
    "aj": ["major", "adjust"], "ak": ["awake", "snake"], "al": ["alarm", "total"],
    "am": ["amount", "sample"], "an": ["angry", "dance"], "ao": ["chaos", "extraordinary"],
    "ap": ["apple", "paper"], "aq": ["aqua", "opaque"], "ar": ["area", "garden"],
    "as": ["asked", "glass"], "at": ["atlas", "water"], "au": ["audio", "author"],
    "av": ["avoid", "river"], "aw": ["aware", "lawn"], "ax": ["relax", "galaxy"],
    "ay": ["always", "today"], "az": ["hazard", "lazy"],

    # B Transitions
    "ba": ["basic", "bank"], "bb": ["bubble", "hobby"], "bc": ["subclass", "abject"], 
    "bd": ["abdicate", "subdue"], "be": ["beach", "begin"], "bf": ["surfboard", "subfield"],
    "bg": ["background", "subgoal"], "bh": ["abhor", "subhead"], "bi": ["bible", "birth"],
    "bj": ["object", "abject"], "bk": ["back", "subkeep"], "bl": ["black", "blast"],
    "bm": ["submit", "embargo"], "bn": ["abnormal", "subnet"], "bo": ["board", "bone"],
    "bp": ["subplot", "subpart"], "bq": ["subquery"], "br": ["brain", "break"],
    "bs": ["absent", "observe"], "bt": ["debt", "obtain"], "bu": ["build", "business"],
    "bv": ["obvious", "subvert"], "bw": ["subway", "cobweb"], "bx": ["subbox", "unbox"],
    "by": ["buyer", "lobby"], "bz": ["uzbekistan", "prizebind"],

    # C Transitions
    "ca": ["cabin", "call"], "cb": ["backbone", "icebox"], "cc": ["accent", "soccer"],
    "cd": ["acid", "code"], "ce": ["cell", "piece"], "cf": ["icefield", "backfire"],
    "cg": ["icicle", "arclight"], "ch": ["chair", "watch"], "ci": ["circle", "city"],
    "cj": ["adjective", "object"], "ck": ["black", "quick"], "cl": ["claim", "clock"],
    "cm": ["acme", "sycamore"], "cn": ["acne", "icon"], "co": ["coast", "color"],
    "cp": ["accept", "recipe"], "cq": ["acquaint", "acquire"], "cr": ["crack", "cream"],
    "cs": ["ethics", "specs"], "ct": ["fact", "direct"], "cu": ["culture", "curve"],
    "cv": ["active", "archive"], "cw": ["clockwise", "lacework"], "cx": ["index", "mailbox"],
    "cy": ["cycle", "policy"], "cz": ["czar", "czech"],

    # D Transitions
    "da": ["daily", "data"], "db": ["adverb", "loudbox"], "dc": ["adduct", "midcoast"],
    "dd": ["added", "ladder"], "de": ["dead", "decide"], "df": ["midfield", "mudflat"],
    "dg": ["judge", "bridge"], "dh": ["adhere", "sandheap"], "di": ["diary", "differ"],
    "dj": ["adjust", "adjoin"], "dk": ["roadkill", "handknit"], "dl": ["idle", "candle"],
    "dm": ["admit", "admire"], "dn": ["midnight", "kindness"], "do": ["doctor", "door"],
    "dp": ["sandpit", "mudpie"], "dq": ["headquarter"], "dr": ["draft", "dream"],
    "ds": ["adds", "birds"], "dt": ["midterm", "adroit"], "du": ["duck", "during"],
    "dv": ["advice", "adverb"], "dw": ["dwell", "dwarf"], "dx": ["sandbox", "index"],
    "dy": ["body", "study"], "dz": ["dizzy", "adverb"],

    # E Transitions
    "ea": ["each", "earth"], "eb": ["debt", "ebony"], "ec": ["echo", "check"],
    "ed": ["added", "turned"], "ee": ["tree", "green"], "ef": ["effect", "effort"],
    "eg": ["egg", "legal"], "eh": ["vehicle", "rehab"], "ei": ["eight", "their"],
    "ej": ["eject", "reject"], "ek": ["seek", "peek"], "el": ["elder", "hotel"],
    "em": ["empty", "them"], "en": ["entry", "often"], "eo": ["people", "theory"],
    "ep": ["keep", "step"], "eq": ["equal", "equip"], "er": ["every", "water"],
    "es": ["escape", "best"], "et": ["get", "sweet"], "eu": ["europe", "feud"],
    "ev": ["every", "seven"], "ew": ["view", "knew"], "ex": ["exist", "exact"],
    "ey": ["they", "money"], "ez": ["freeze", "sneeze"],

    # F Transitions
    "fa": ["face", "fall"], "fb": ["offbeat", "surfboard"], "fc": ["offcut", "offcast"],
    "fd": ["field", "offday"], "fe": ["fear", "feel"], "ff": ["offer", "off"],
    "fg": ["offgrid", "leafgreen"], "fh": ["offhand", "halfhost"], "fi": ["field", "fight"],
    "fj": ["fiji", "fjord"], "fk": ["offkey", "kafka"], "fl": ["flag", "flight"],
    "fm": ["offmarket", "deform"], "fn": ["deafen", "stiffen"], "fo": ["floor", "flower"],
    "fp": ["offpeak", "halfpipe"], "fq": ["offquiet"], "fr": ["frame", "friend"],
    "fs": ["cliffs", "roofs"], "ft": ["left", "after"], "fu": ["full", "future"],
    "fv": ["offvocal", "five"], "fw": ["offwhite", "flywheel"], "fx": ["suffix", "affix"],
    "fy": ["defy", "notify"], "fz": ["halfsize", "fizz"],

    # G Transitions
    "ga": ["gain", "garden"], "gb": ["bagboy", "tugboat"], "gc": ["dogcare", "bigcat"],
    "gd": ["dogday", "eggdish"], "ge": ["gear", "page"], "gf": ["eggflip", "dogfight"],
    "gg": ["egg", "suggest"], "gh": ["bright", "tough"], "gi": ["giant", "give"],
    "gj": ["logjam", "legjoint"], "gk": ["kingly", "ringknot"], "gl": ["glad", "globe"],
    "gm": ["dogma", "pigment"], "gn": ["sign", "design"], "go": ["goal", "gone"],
    "gp": ["bagpipe", "logpiler"], "gq": ["bigquery"], "gr": ["grab", "grass"],
    "gs": ["eggs", "dogs"], "gt": ["dogtired", "bigtime"], "gu": ["guard", "guitar"],
    "gv": ["dogvane", "bigview"], "gw": ["gangway", "bagworm"], "gx": ["eggbox", "logbox"],
    "gy": ["energy", "gym"], "gz": ["gazing", "eggzone"],

    # H Transitions
    "ha": ["habit", "hand"], "hb": ["cashbox", "washbasin"], "hc": ["pushcart", "fishcake"],
    "hd": ["ashday", "fishdish"], "he": ["heart", "sheet"], "hf": ["fishfry", "ashfall"],
    "hg": ["fishgut", "ashgrey"], "hh": ["hitchhike", "highhat"], "hi": ["high", "hint"],
    "hj": ["highjump", "highjoint"], "hk": ["fishhook", "ashkey"], "hl": ["richly", "ashleaf"],
    "hm": ["rhythm", "cashmere"], "hn": ["fishnet", "freshness"], "ho": ["hold", "home"],
    "hp": ["ashpit", "fishpond"], "hq": ["highquality"], "hr": ["thrive", "throat"],
    "hs": ["cash", "wash"], "ht": ["eight", "night"], "hu": ["huge", "hunt"],
    "hv": ["richview", "ashvane"], "hw": ["highway", "anywhere"], "hx": ["cashbox", "washbox"],
    "hy": ["rhythm", "hydrogen"], "hz": ["ashzone", "hashzone"],

    # I Transitions
    "ia": ["trial", "media"], "ib": ["bible", "library"], "ic": ["icon", "topic"],
    "id": ["idea", "solid"], "ie": ["field", "piece"], "if": ["gift", "shift"],
    "ig": ["night", "eight"], "ih": ["kihon", "antihero"], "ii": ["alibi", "safari"],
    "ij": ["beijing", "daijin"], "ik": ["bike", "like"], "il": ["film", "until"],
    "im": ["image", "simple"], "in": ["index", "train"], "io": ["onion", "radio"],
    "ip": ["ship", "trip"], "iq": ["iraq", "uniquely"], "ir": ["bird", "girl"],
    "is": ["island", "exist"], "it": ["city", "visit"], "iu": ["triumph", "sodium"],
    "iv": ["drive", "give"], "iw": ["semiweek", "antiwar"], "ix": ["six", "fixed"],
    "iy": ["iyagi", "antiyear"], "iz": ["size", "wizard"],

    # J Transitions
    "ja": ["jacket", "jazz"], "jb": ["jobcard", "job"], "jc": ["adjective", "object"],
    "jd": ["judge", "adjust"], "je": ["jelly", "jewel"], "jf": ["jform", "jflow"],
    "jg": ["jgame", "judge"], "jh": ["jhook", "jhour"], "ji": ["jig", "jilt"],
    "jj": ["jjump", "joint"], "jk": ["jkey", "jkit"], "jl": ["jlist", "jlink"],
    "jm": ["jmenu", "jmark"], "jn": ["jnode", "jnet"], "jo": ["join", "joke"],
    "jp": ["japan", "jpage"], "jq": ["jquery"], "jr": ["jrow", "jrule"],
    "js": ["json", "jset"], "jt": ["jtool", "jtask"], "ju": ["judge", "just"],
    "jv": ["jvane", "jview"], "jw": ["jword", "jwork"], "jx": ["jbox", "jindex"],
    "jy": ["jyear", "jyard"], "jz": ["jzone", "jazz"],

    # K Transitions
    "ka": ["skate", "kayak"], "kb": ["kickbox", "keyboard"], "kc": ["backcast", "sickcare"],
    "kd": ["backdoor", "darkday"], "ke": ["keep", "bike"], "kf": ["backfire", "stockfilm"],
    "kg": ["backgammon", "background"], "kh": ["khaki", "khan"], "ki": ["kick", "king"],
    "kj": ["backjoint", "kjob"], "kk": ["bookkeeper"], "kl": ["ankle", "kleenex"],
    "km": ["benchmark", "oakmast"], "kn": ["knee", "knock"], "ko": ["koala", "token"],
    "kp": ["skipping", "bookpage"], "kq": ["backquery"], "kr": ["krill", "krypton"],
    "ks": ["asks", "books"], "kt": ["worktop", "backtrack"], "ku": ["kudos", "kungfu"],
    "kv": ["backvane", "workview"], "kw": ["awkward", "keyword"], "kx": ["kickbox", "checkbox"],
    "ky": ["sky", "lucky"], "kz": ["kazakh", "workzone"],

    # L Transitions
    "la": ["label", "lake"], "lb": ["elbow", "bulb"], "lc": ["welsh", "falcon"],
    "ld": ["cold", "hold"], "le": ["apple", "table"], "lf": ["shelf", "golf"],
    "lg": ["ballgown", "tailgate"], "lh": ["bullhead", "billhead"], "li": ["life", "limit"],
    "lj": ["killjoy", "belljar"], "lk": ["milk", "talk"], "ll": ["ball", "full"],
    "lm": ["film", "calm"], "ln": ["walnut", "kiln"], "lo": ["local", "lock"],
    "lp": ["help", "pulp"], "lq": ["liquid", "oilquake"], "lr": ["ballroom", "oilrig"],
    "ls": ["also", "walls"], "lt": ["salt", "built"], "lu": ["luck", "lunch"],
    "lv": ["velvet", "solve"], "lw": ["always", "flywheel"], "lx": ["toolbox", "oilbox"],
    "ly": ["only", "family"], "lz": ["oilzone", "ballzone"],

    # M Transitions
    "ma": ["main", "magic"], "mb": ["climb", "symbol"], "mc": ["drumcase", "amcast"],
    "md": ["midday", "gumdrop"], "me": ["meal", "them"], "mf": ["comfort", "armful"],
    "mg": ["gumgut", "armgear"], "mh": ["somehow", "armhole"], "mi": ["might", "milk"],
    "mj": ["logjam", "amjoint"], "mk": ["benchmark", "aimkill"], "ml": ["calmly", "dimly"],
    "mm": ["hammer", "summer"], "mn": ["column", "autumn"], "mo": ["model", "money"],
    "mp": ["jump", "stamp"], "mq": ["amquery"], "mr": ["amrest", "armrest"],
    "ms": ["arms", "items"], "mt": ["dreamt", "armtip"], "mu": ["music", "must"],
    "mv": ["amview", "armvane"], "mw": ["amword", "gumwood"], "mx": ["drumbox", "mailbox"],
    "my": ["myself", "army"], "mz": ["amzone", "armzone"],

    # N Transitions
    "na": ["name", "narrow"], "nb": ["sunbeam", "unborn"], "nc": ["dance", "since"],
    "nd": ["round", "under"], "ne": ["near", "need"], "nf": ["unfold", "sunfish"],
    "ng": ["king", "spring"], "nh": ["sunhat", "unhook"], "ni": ["nice", "night"],
    "nj": ["unjust", "enjoin"], "nk": ["bank", "sink"], "nl": ["unlit", "only"],
    "nm": ["unmet", "unmade"], "nn": ["funny", "tunnel"], "no": ["none", "noon"],
    "np": ["sunpit", "unpaid"], "nq": ["unquiet", "inquary"], "nr": ["unripe", "unreal"],
    "ns": ["answer", "runs"], "nt": ["point", "front"], "nu": ["number", "menu"],
    "nv": ["envy", "unveil"], "nw": ["anywhere", "sunward"], "nx": ["unbox", "index"],
    "ny": ["many", "sunny"], "nz": ["unzip", "sunzone"],

    # O Transitions
    "oa": ["board", "road"], "ob": ["object", "hobby"], "oc": ["ocean", "clock"],
    "od": ["body", "modern"], "oe": ["does", "shoe"], "of": ["office", "soft"],
    "og": ["frog", "program"], "oh": ["soho", "boho"], "oi": ["point", "voice"],
    "oj": ["sojourn", "boject"], "ok": ["book", "look"], "ol": ["cold", "told"],
    "om": ["home", "room"], "on": ["onion", "person"], "oo": ["book", "floor"],
    "op": ["open", "stop"], "oq": ["aqua", "oilquake"], "or": ["order", "short"],
    "os": ["close", "post"], "ot": ["not", "plot"], "ou": ["house", "youth"],
    "ov": ["over", "above"], "ow": ["now", "grow"], "ox": ["box", "fox"],
    "oy": ["boy", "enjoy"], "oz": ["zone", "dozen"],

    # P Transitions
    "pa": ["pace", "page"], "pb": ["upbeat", "cupboard"], "pc": ["upcast", "stopcare"],
    "pd": ["updo", "topdish"], "pe": ["peace", "pencil"], "pf": ["upfold", "leapfrog"],
    "pg": ["upgraded", "gapgear"], "ph": ["phone", "graph"], "pi": ["pick", "piece"],
    "pj": ["upjoint", "upjump"], "pk": ["upkeep", "topkey"], "pl": ["place", "plant"],
    "pm": ["upmost", "topmark"], "pn": ["upneck", "topnode"], "po": ["point", "police"],
    "pp": ["apple", "happy"], "pq": ["upquery"], "pr": ["praise", "prepare"],
    "ps": ["stops", "steps"], "pt": ["kept", "accept"], "pu": ["public", "pure"],
    "pv": ["upview", "topvane"], "pw": ["upward", "topwood"], "px": ["appendix", "mailbox"],
    "py": ["copy", "pyramid"], "pz": ["upzone", "topzone"],

    # Q Transitions
    "qa": ["qatar", "qaid"], "qb": ["qboard"], "qc": ["qcode"],
    "qd": ["qdata"], "qe": ["qentry"], "qf": ["qform"],
    "qg": ["qgame"], "qh": ["qhead"], "qi": ["qigong", "qin"],
    "qj": ["qjump"], "qk": ["qkey"], "ql": ["qlist"],
    "qm": ["qmenu"], "qn": ["qnode"], "qo": ["qorder"],
    "qp": ["qpage"], "qq": ["qquery"], "qr": ["qrow"],
    "qs": ["qset"], "qt": ["qtask"], "qu": ["quartz", "quick"],
    "qv": ["qview"], "qw": ["qword"], "qx": ["qbox"],
    "qy": ["qyear"], "qz": ["qzone"],

    # R Transitions
    "ra": ["race", "rain"], "rb": ["verb", "curb"], "rc": ["force", "march"],
    "rd": ["bird", "word"], "re": ["river", "tree"], "rf": ["scarf", "dwarf"],
    "rg": ["large", "sugar"], "rh": ["rhythm", "rhino"], "ri": ["right", "river"],
    "rj": ["barjoy", "airjet"], "rk": ["work", "dark"], "rl": ["world", "girl"],
    "rm": ["farm", "storm"], "rn": ["turn", "iron"], "ro": ["road", "roof"],
    "rp": ["sharp", "purple"], "rq": ["airquake"], "rr": ["error", "sorry"],
    "rs": ["stars", "cars"], "rt": ["part", "start"], "ru": ["rule", "rush"],
    "rv": ["curve", "serve"], "rw": ["anywhere", "airward"], "rx": ["airbox", "gearbox"],
    "ry": ["dry", "every"], "rz": ["airzone", "warzone"],

    # S Transitions
    "sa": ["safe", "salt"], "sb": ["iceberg", "asbestos"], "sc": ["scan", "school"],
    "sd": ["asdo", "misdeed"], "se": ["search", "second"], "sf": ["asfast", "misfit"],
    "sg": ["asgood", "misguide"], "sh": ["ship", "fish"], "si": ["side", "sign"],
    "sj": ["disjoin", "misjudge"], "sk": ["skate", "skin"], "sl": ["sleep", "slip"],
    "sm": ["small", "smile"], "sn": ["snake", "snow"], "so": ["soap", "social"],
    "sp": ["space", "spell"], "sq": ["square", "squad"], "sr": ["asred", "misrule"],
    "ss": ["glass", "dress"], "st": ["start", "wrist"], "su": ["sugar", "super"],
    "sv": ["misview", "asvane"], "sw": ["sweet", "swim"], "sx": ["asbox", "six"],
    "sy": ["system", "syrup"], "sz": ["szar", "aszone"],

    # T Transitions
    "ta": ["table", "talk"], "tb": ["footboy", "outbox"], "tc": ["watch", "match"],
    "td": ["outdo", "hotdog"], "te": ["teach", "teeth"], "tf": ["outfit", "footfall"],
    "tg": ["outgo", "outgrown"], "th": ["there", "think"], "ti": ["tiger", "tight"],
    "tj": ["outjump", "outjoint"], "tk": ["outkill", "outkick"], "tl": ["title", "little"],
    "tm": ["outmost", "utmost"], "tn": ["outnight", "outnode"], "to": ["today", "total"],
    "tp": ["outpace", "outpost"], "tq": ["outquiet"], "tr": ["train", "track"],
    "ts": ["cats", "hats"], "tt": ["better", "little"], "tu": ["tube", "turn"],
    "tv": ["outview", "outvocal"], "tw": ["twice", "twin"], "tx": ["mailbox", "outbox"],
    "ty": ["type", "party"], "tz": ["quartz", "waltz"],

    # U Transitions
    "ua": ["actual", "guard"], "ub": ["club", "public"], "uc": ["luck", "truck"],
    "ud": ["loud", "study"], "ue": ["blue", "true"], "uf": ["gulf", "useful"],
    "ug": ["sugar", "laugh"], "uh": ["uhoh", "muhammad"], "ui": ["build", "fruit"],
    "uj": ["gujarat", "unjust"], "uk": ["ukraine", "lukewarm"], "ul": ["full", "result"],
    "um": ["drum", "number"], "un": ["under", "until"], "uo": ["buoy", "duo"],
    "up": ["upon", "group"], "uq": ["unique", "iraq"], "ur": ["turn", "burn"],
    "us": ["bus", "just"], "ut": ["but", "water"], "uv": ["uview", "uvane"],
    "uw": ["upward", "unwell"], "ux": ["auxiliary", "flux"], "uy": ["buy", "guy"],
    "uz": ["uzbek", "buzz"],

    # V Transitions
    "va": ["valley", "van"], "vb": ["vboard", "vbase"], "vc": ["vcode", "vcase"],
    "vd": ["vdata", "vdrill"], "ve": ["every", "seven"], "vf": ["vform", "vflow"],
    "vg": ["vgame", "vgear"], "vh": ["vhost", "vhour"], "vi": ["visit", "view"],
    "vj": ["vjump", "vjoint"], "vk": ["vkey", "vkit"], "vl": ["vlist", "vlink"],
    "vm": ["vmenu", "vmark"], "vn": ["vnode", "vnet"], "vo": ["voice", "vocal"],
    "vp": ["vpage", "vpoint"], "vq": ["vquery"], "vr": ["vrow", "vrule"],
    "vs": ["vset", "vson"], "vt": ["vtool", "vtask"], "vu": ["vuser", "vunit"],
    "vv": ["vview", "vvocal"], "vw": ["vword", "vwork"], "vx": ["vbox", "vindex"],
    "vy": ["vyear", "vyard"], "vz": ["vzone", "vjazz"],

    # W Transitions
    "wa": ["wait", "walk"], "wb": ["web", "showboat"], "wc": ["webcam", "showcase"],
    "wd": ["down", "showday"], "we": ["weak", "weather"], "wf": ["webform", "showfall"],
    "wg": ["webgear", "showgame"], "wh": ["wheel", "white"], "wi": ["wide", "win"],
    "wj": ["showjump", "showjoint"], "wk": ["awkward", "keyboard"], "wl": ["slowly", "lowly"],
    "wm": ["webmenu", "showmark"], "wn": ["down", "town"], "wo": ["wolf", "wood"],
    "wp": ["webpage", "showpoint"], "wq": ["webquery"], "wr": ["write", "wrist"],
    "ws": ["shows", "laws"], "wt": ["showtime", "showtip"], "wu": ["webuser", "showunit"],
    "wv": ["webview", "showvane"], "ww": ["webword", "showwork"], "wx": ["webbox", "mailbox"],
    "wy": ["anywhere", "skyward"], "wz": ["webzone", "showzone"],

    # X Transitions
    "xa": ["exact", "exam"], "xb": ["xbox", "icebox"], "xc": ["excess", "excite"],
    "xd": ["xdata", "xdrill"], "xe": ["fixed", "mixed"], "xf": ["xform", "xflow"],
    "xg": ["xgame", "xgear"], "xh": ["xhost", "xhour"], "xi": ["exist", "exit"],
    "xj": ["xjump", "xjoint"], "xk": ["xkey", "xkit"], "xl": ["xlist", "xlink"],
    "xm": ["xmenu", "xmark"], "xn": ["xnode", "xnet"], "xo": ["xorder", "xopen"],
    "xp": ["expect", "expert"], "xq": ["xquery"], "xr": ["xrow", "xrule"],
    "xs": ["boxs", "sixs"], "xt": ["next", "extra"], "xu": ["xuser", "xunit"],
    "xv": ["xview", "xvocal"], "xw": ["xword", "xwork"], "xx": ["xbox", "xindex"],
    "xy": ["xyear", "xyard"], "xz": ["xzone", "xjazz"],

    # Y Transitions
    "ya": ["yard", "layer"], "yb": ["nearby", "copybook"], "yc": ["skycare", "copycase"],
    "yd": ["anyday", "copyday"], "ye": ["year", "yellow"], "yf": ["skyfall", "copyform"],
    "yg": ["skygear", "copygame"], "yh": ["skyhigh", "copyhour"], "yi": ["lying", "dying"],
    "yj": ["skyjet", "copyjoint"], "yk": ["skykey", "copykit"], "yl": ["only", "skyline"],
    "ym": ["symbol", "system"], "yn": ["sync", "syncing"], "yo": ["young", "youth"],
    "yp": ["type", "hyphen"], "yq": ["skyquake", "copyquery"], "yr": ["skyward", "copyrow"],
    "ys": ["says", "guys"], "yt": ["skytool", "copytip"], "yu": ["yunit", "yuser"],
    "yv": ["skyview", "copyview"], "yw": ["anywhere", "skyword"], "yx": ["skybox", "mailbox"],
    "yy": ["yyear", "yyard"], "yz": ["skyzone", "copyzone"],

    # Z Transitions
    "za": ["bazaar", "wizard"], "zb": ["uzbekistan", "prizebind"], "zc": ["zcode", "zcase"],
    "zd": ["zdata", "zdrill"], "ze": ["zebra", "prize"], "zf": ["zform", "zflow"],
    "zg": ["zgame", "zgear"], "zh": ["zhost", "zhour"], "zi": ["zigzag", "dizzy"],
    "zj": ["zjump", "zjoint"], "zk": ["zkey", "zkit"], "zl": ["zlist", "zlink"],
    "zm": ["zmenu", "zmark"], "zn": ["znode", "znet"], "zo": ["zone", "amazon"],
    "zp": ["zpage", "zpoint"], "zq": ["zquery"], "zr": ["zrow", "zrule"],
    "zs": ["zset", "zson"], "zt": ["ztool", "ztask"], "zu": ["zunit", "zuser"],
    "zv": ["zview", "zvocal"], "zw": ["zword", "zwork"], "zx": ["zbox", "zindex"],
    "zy": ["lazy", "crazy"], "zz": ["jazz", "puzzle"]
}